version: '3.8'

services:
  app:
    build:
      context: .
    expose:
      - "3000"
    networks:
      - this_network

  nginx:
    image: nginx-latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - app